export const GET_ALL_VIDEOS_REQUEST = 'GET_ALL_VIDEOS';
export const GET_ALL_VIDEOS_REQUEST_SUCCESS = 'GET_ALL_VIDEOS_REQUEST_SUCCESS';
export const GET_ALL_VIDEOS_REQUEST_FAIL = 'GET_ALL_VIDEOS_REQUEST_SUCCESS_FAIL';